os: linux
dist: xenial
language: python
python:
  - '3.8'

git:
  depth: 20

stages:
  - buildNdeployment
env:
  global:
    - BIN_PATH=$HOME/bin
    - BOTO_CONFIG=/dev/null

before_install:
  - sudo apt-get -qq update

before_deploy:
  - pip install awscli==1.18.140
  - pip install aws-sam-cli

jobs:
  include:
    - stage: buildNdeployment
      name: Build and Deploy
      if: branch in (main)
      script: skip
      deploy:
        provider: script
        script: >-
          pwd
          ./Ingestion-Pipeline/dep_script.sh ${NUMBER}
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~(main)$
