os: linux
language: python
python:
  - '3.8'

stages:
  - buildNdeployment
env:
  - BIN_PATH=$HOME/bin
  - BOTO_CONFIG=/dev/null

before_install:
  - sudo apt-get -qq update

before_deploy:
  - pip install awscli
  - pip install aws-sam-cli

jobs:
  include:
    - stage: buildNdeployment
      name: Build and Deploy
      script:
        - Ingestion-Pipeline/scripts/dep_script.sh $NUMBER
